apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: website
    app.kubernetes.io/instance: myargoapp1
  name: website
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: website
  type: LoadBalancer
status:
  loadBalancer: {}